services:
    web:
        container_name: torrentstream
        env_file:
            - .env
        image: ghcr.io/msuchail/torrentstream
        networks:
            - default
            - caddy
        restart: unless-stopped
        volumes:
            - ./download:/var/www/html/download
        depends_on:
            - mysql
            - transmission
            - redis

    mysql:
        env_file:
            - .env
        image: mysql
        restart: unless-stopped
        networks:
            - default
        volumes:
            - ./mysql-data:/var/lib/mysql

    redis:
        image: redis
        restart: unless-stopped
        networks:
            - default
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            -   ./redis-data:/data

networks:
    default:
    caddy:
        external: true
