services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      PUID: 33
      PGID: 33
      TZ: 'Europe/London'
    volumes:
      - ./storage/private/torrents:/torrents
      - ./storage/public/downloads:/downloads
    restart: unless-stopped

  web:
    container_name: torrentstream
    env_file:
      - .env
    image: ghcr.io/msuchail/torrentstream
    volumes:
      - ./storage:/var/www/html/storage/app
#    networks:
#      - caddy
    restart: unless-stopped
    depends_on:
      transmission:
        condition: service_started
      mysql:
        condition: service_healthy
    ports:
      - 80:8080

  queue:
    env_file:
      - .env
    environment:
      - AUTORUN_ENABLED = false
    image: ghcr.io/msuchail/torrentstream
    deploy:
      mode: replicated
      replicas: 3
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/html/storage/app
    depends_on:
      transmission:
        condition: service_started
      mysql:
        condition: service_healthy
    stop_signal: SIGTERM
    healthcheck:
      # This is our native healthcheck script for the queue
      test: [ "CMD", "healthcheck-queue" ]
      start_period: 10s
    command: php artisan queue:work --timeout=7200

  mysql:
    ports:
      -   3306:3306
    env_file:
      - .env
    image: mysql
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

#networks:
#  caddy:
#    external: true
