apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrentstream-app
  labels:
    app: torrentstream-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: torrentstream-app
  template:
      metadata:
        labels:
            app: torrentstream-app
      spec:
        containers:
            - name: torrentstream-app
              image: ghcr.io/msuchail/torrentstream:latest
              ports:
                  - containerPort: 8080
              envFrom:
                - configMapRef:
                    name: torrentstream-map
                - secretRef:
                    name: torrentstream-secrets
              env:
                - name: AUTORUN_ENABLED
                  value: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrentstream-queue
  labels:
    app: torrentstream-queue

spec:
  replicas: 3
  selector:
    matchLabels:
      app: torrentstream-queue
  template:
    metadata:
      labels:
        app: torrentstream-queue
    spec:
      containers:
        - name: torrentstream-queue
          image: ghcr.io/msuchail/torrentstream:latest
          command: ["php", "artisan", "queue:work"]
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: torrentstream-map
            - secretRef:
                name: torrentstream-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: torrentstream-app

spec:
  selector:
    app: torrentstream-app
#  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80

