name: publish

on:
  push:
    branches: [ "master" ]

env:
  CONTAINER_NAME: torrentstream
  WORK_DIR: torrentstream

jobs:
  publish:
    environment: prod
    name: deploy to prod
    runs-on: ubuntu-latest

    steps:
      - name: SSH-Compose
        # You may pin to the exact commit or the version.
        # uses: matiasnu/github-action-ssh-docker-compose@7fb3aa789f898b63c3722e6beb2dafa1a70f0e22
        uses: matiasnu/github-action-ssh-docker-compose@v2.0.3
        with:
          # Private SSH key used for logging into remote system.
          ssh_private_key: ${env.SSH_PRIVATE_KEY}
          # Remote host name.
          ssh_host: ${env.SSH_HOST}
          # Remote user name.
          ssh_user: ${env.SSH_USER}
          # Prefix for docker compose containers.
          docker_compose_prefix: docker
          
          docker_compose_filename: docker-compose.yml
          # Execute docker compose-down ("true" or "false").
          docker_compose_down: true
          
